export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_BURGUER = 'PURCHASE_BURGUER';
export const PURCHASE_BURGUER_START = 'PURCHASE_BURGUER_START';
export const PURCHASE_BURGUER_SUCCESS = 'PURCHASE_BURGUER_SUCCESS';
export const PURCHASE_BURGUER_FAILED = 'PURCHASE_BURGUER_FAILED';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_BEGIN_AUTHENTICATION = 'AUTH_BEGIN_AUTHENTICATION';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_LOGIN = 'AUTH_CHECK_LOGIN';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';